# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
      TOXENV: py35
    Python36:
      python.version: '3.6'
      TOXENV: py36
    Python37:
      python.version: '3.7'
      TOXENV: py37
    Python38:
      python.version: '3.8'
      TOXENV: py38

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -U pip setuptools virtualenv tox
  displayName: 'Install dependencies'

- script: |
    tox -e%TOXENV%
  displayName: 'Run tests'

- bash: |
    set -e
    pip install -U junitxml
    mkdir -p junit
    stestr last --subunit | tools/subunit_to_junit.py -o junit/test-results.xml
  condition: succeededOrFailed()
  displayName: 'Generate results'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Test results for Windows Python $(python.version)'
